'use client';

import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { 
  Video, Clock, Users, Download, 
  ExternalLink, Play, FileText
} from 'lucide-react';

interface Meeting {
  id: string;
  title: string;
  date: string;
  duration: number;
  participants: string[];
  actions: number;
  status: 'completed' | 'processing' | 'failed';
  hasRecording: boolean;
  hasTranscript: boolean;
}

interface MeetingsListProps {
  meetings: Meeting[];
}

export function MeetingsList({ meetings }: MeetingsListProps) {
  const [expandedMeeting, setExpandedMeeting] = useState<string | null>(null);

  const handleViewDetails = (meetingId: string) => {
    alert(`📊 Meeting Details\n\nID: ${meetingId}\n\nFull meeting details would show:\n- Complete transcript\n- All participants\n- Action items breakdown\n- Time markers\n\n(Connect to Supabase to see real data)`);
  };

  const handleViewActions = (meetingId: string) => {
    const meeting = meetings.find(m => m.id === meetingId);
    if (meeting) {
      alert(`✅ ${meeting.actions} Actions from "${meeting.title}"\n\nThis would show all action items extracted from this specific meeting.\n\n(Connect to Supabase to see real actions)`);
    }
  };

  const handleDownloadTranscript = (meetingId: string) => {
    const meeting = meetings.find(m => m.id === meetingId);
    if (meeting) {
      // Create sample transcript
      const transcript = `Meeting: ${meeting.title}
Date: ${new Date(meeting.date).toLocaleDateString()}
Duration: ${meeting.duration} minutes
Participants: ${meeting.participants.join(', ')}

[Sample Transcript]

This is a sample transcript. In production, this would contain the full meeting transcript from Zoom.

Key Discussion Points:
- Project timeline review
- Resource allocation
- Next steps and action items

Action Items Extracted: ${meeting.actions}

---
Generated by MeetingActions
      `;

      const blob = new Blob([transcript], { type: 'text/plain' });
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${meeting.title.replace(/\s+/g, '-').toLowerCase()}-transcript.txt`;
      a.click();
      window.URL.revokeObjectURL(url);
    }
  };

  const handleExportAll = () => {
    const csv = [
      ['Title', 'Date', 'Duration (min)', 'Participants', 'Actions', 'Status'].join(','),
      ...meetings.map(m => [
        `"${m.title}"`,
        new Date(m.date).toLocaleDateString(),
        m.duration,
        m.participants.length,
        m.actions,
        m.status
      ].join(','))
    ].join('\n');

    const blob = new Blob([csv], { type: 'text/csv' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `meetings-${new Date().toISOString().split('T')[0]}.csv`;
    a.click();
    window.URL.revokeObjectURL(url);
  };

  return (
    <>
      <div className="mb-8 flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold mb-2">Meetings</h1>
          <p className="text-gray-600">
            View all your processed meetings and their action items.
          </p>
        </div>
        <Button onClick={handleExportAll}>
          <Download className="mr-2 h-4 w-4" />
          Export All
        </Button>
      </div>

      <div className="space-y-4">
        {meetings.map((meeting) => (
          <Card key={meeting.id} className="hover:shadow-lg transition">
            <CardContent className="pt-6">
              <div className="flex items-start justify-between">
                <div className="flex-1">
                  <div className="flex items-center gap-3 mb-3">
                    <div className="h-12 w-12 bg-blue-100 rounded-lg flex items-center justify-center">
                      <Video className="h-6 w-6 text-blue-600" />
                    </div>
                    <div>
                      <h3 className="font-semibold text-lg">{meeting.title}</h3>
                      <div className="flex items-center gap-4 text-sm text-gray-600 mt-1">
                        <span className="flex items-center gap-1">
                          <Clock className="h-4 w-4" />
                          {new Date(meeting.date).toLocaleDateString('en-US', {
                            month: 'short',
                            day: 'numeric',
                            hour: 'numeric',
                            minute: '2-digit',
                          })}
                        </span>
                        <span>{meeting.duration} min</span>
                        <span className="flex items-center gap-1">
                          <Users className="h-4 w-4" />
                          {meeting.participants.length} participants
                        </span>
                      </div>
                    </div>
                  </div>

                  <div className="flex items-center gap-3 mb-4">
                    <Badge variant="outline" className="bg-green-50 text-green-700 border-green-200">
                      {meeting.actions} actions extracted
                    </Badge>
                    <Badge variant="outline">
                      {meeting.status}
                    </Badge>
                    {meeting.hasRecording && (
                      <Badge variant="secondary">
                        <Play className="h-3 w-3 mr-1" />
                        Recording
                      </Badge>
                    )}
                    {meeting.hasTranscript && (
                      <Badge variant="secondary">
                        <FileText className="h-3 w-3 mr-1" />
                        Transcript
                      </Badge>
                    )}
                  </div>

                  <div className="flex items-center gap-2 flex-wrap">
                    <Button 
                      size="sm" 
                      variant="outline"
                      onClick={() => handleViewDetails(meeting.id)}
                    >
                      View Details
                      <ExternalLink className="ml-2 h-4 w-4" />
                    </Button>
                    <Button 
                      size="sm" 
                      variant="outline"
                      onClick={() => handleViewActions(meeting.id)}
                    >
                      View Actions ({meeting.actions})
                    </Button>
                    {meeting.hasTranscript && (
                      <Button 
                        size="sm" 
                        variant="outline"
                        onClick={() => handleDownloadTranscript(meeting.id)}
                      >
                        <Download className="mr-2 h-4 w-4" />
                        Download Transcript
                      </Button>
                    )}
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>
        ))}
      </div>
    </>
  );
}

